# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from src.protos import model_service_pb2 as src_dot_protos_dot_model__service__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in src/protos/model_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ModelServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.EmbedText = channel.unary_unary(
                '/model_service.ModelService/EmbedText',
                request_serializer=src_dot_protos_dot_model__service__pb2.EmbedTextRequest.SerializeToString,
                response_deserializer=src_dot_protos_dot_model__service__pb2.EmbedTextResponse.FromString,
                _registered_method=True)
        self.EmbedImage = channel.unary_unary(
                '/model_service.ModelService/EmbedImage',
                request_serializer=src_dot_protos_dot_model__service__pb2.EmbedImageRequest.SerializeToString,
                response_deserializer=src_dot_protos_dot_model__service__pb2.EmbedImageResponse.FromString,
                _registered_method=True)
        self.EmbedImageBatch = channel.unary_unary(
                '/model_service.ModelService/EmbedImageBatch',
                request_serializer=src_dot_protos_dot_model__service__pb2.EmbedImageBatchRequest.SerializeToString,
                response_deserializer=src_dot_protos_dot_model__service__pb2.EmbedImageBatchResponse.FromString,
                _registered_method=True)


class ModelServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def EmbedText(self, request, context):
        """Get text embedding
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def EmbedImage(self, request, context):
        """Get embedding for a single image
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def EmbedImageBatch(self, request, context):
        """Get embeddings for a batch of images (highly efficient for video frames)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ModelServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'EmbedText': grpc.unary_unary_rpc_method_handler(
                    servicer.EmbedText,
                    request_deserializer=src_dot_protos_dot_model__service__pb2.EmbedTextRequest.FromString,
                    response_serializer=src_dot_protos_dot_model__service__pb2.EmbedTextResponse.SerializeToString,
            ),
            'EmbedImage': grpc.unary_unary_rpc_method_handler(
                    servicer.EmbedImage,
                    request_deserializer=src_dot_protos_dot_model__service__pb2.EmbedImageRequest.FromString,
                    response_serializer=src_dot_protos_dot_model__service__pb2.EmbedImageResponse.SerializeToString,
            ),
            'EmbedImageBatch': grpc.unary_unary_rpc_method_handler(
                    servicer.EmbedImageBatch,
                    request_deserializer=src_dot_protos_dot_model__service__pb2.EmbedImageBatchRequest.FromString,
                    response_serializer=src_dot_protos_dot_model__service__pb2.EmbedImageBatchResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'model_service.ModelService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('model_service.ModelService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ModelService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def EmbedText(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/model_service.ModelService/EmbedText',
            src_dot_protos_dot_model__service__pb2.EmbedTextRequest.SerializeToString,
            src_dot_protos_dot_model__service__pb2.EmbedTextResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def EmbedImage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/model_service.ModelService/EmbedImage',
            src_dot_protos_dot_model__service__pb2.EmbedImageRequest.SerializeToString,
            src_dot_protos_dot_model__service__pb2.EmbedImageResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def EmbedImageBatch(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/model_service.ModelService/EmbedImageBatch',
            src_dot_protos_dot_model__service__pb2.EmbedImageBatchRequest.SerializeToString,
            src_dot_protos_dot_model__service__pb2.EmbedImageBatchResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
