# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: src/protos/model_service.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'src/protos/model_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1esrc/protos/model_service.proto\x12\rmodel_service\" \n\x10\x45mbedTextRequest\x12\x0c\n\x04text\x18\x01 \x01(\t\"&\n\x11\x45mbedTextResponse\x12\x11\n\tembedding\x18\x01 \x03(\x02\"\'\n\x11\x45mbedImageRequest\x12\x12\n\nimage_data\x18\x01 \x01(\x0c\"\'\n\x12\x45mbedImageResponse\x12\x11\n\tembedding\x18\x01 \x03(\x02\"1\n\x16\x45mbedImageBatchRequest\x12\x17\n\x0fimage_data_list\x18\x01 \x03(\x0c\"G\n\x17\x45mbedImageBatchResponse\x12,\n\nembeddings\x18\x01 \x03(\x0b\x32\x18.model_service.Embedding\"\x1b\n\tEmbedding\x12\x0e\n\x06vector\x18\x01 \x03(\x02\x32\x93\x02\n\x0cModelService\x12N\n\tEmbedText\x12\x1f.model_service.EmbedTextRequest\x1a .model_service.EmbedTextResponse\x12Q\n\nEmbedImage\x12 .model_service.EmbedImageRequest\x1a!.model_service.EmbedImageResponse\x12`\n\x0f\x45mbedImageBatch\x12%.model_service.EmbedImageBatchRequest\x1a&.model_service.EmbedImageBatchResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'src.protos.model_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_EMBEDTEXTREQUEST']._serialized_start=49
  _globals['_EMBEDTEXTREQUEST']._serialized_end=81
  _globals['_EMBEDTEXTRESPONSE']._serialized_start=83
  _globals['_EMBEDTEXTRESPONSE']._serialized_end=121
  _globals['_EMBEDIMAGEREQUEST']._serialized_start=123
  _globals['_EMBEDIMAGEREQUEST']._serialized_end=162
  _globals['_EMBEDIMAGERESPONSE']._serialized_start=164
  _globals['_EMBEDIMAGERESPONSE']._serialized_end=203
  _globals['_EMBEDIMAGEBATCHREQUEST']._serialized_start=205
  _globals['_EMBEDIMAGEBATCHREQUEST']._serialized_end=254
  _globals['_EMBEDIMAGEBATCHRESPONSE']._serialized_start=256
  _globals['_EMBEDIMAGEBATCHRESPONSE']._serialized_end=327
  _globals['_EMBEDDING']._serialized_start=329
  _globals['_EMBEDDING']._serialized_end=356
  _globals['_MODELSERVICE']._serialized_start=359
  _globals['_MODELSERVICE']._serialized_end=634
# @@protoc_insertion_point(module_scope)
