# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: src/protos/video_search.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'src/protos/video_search.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1dsrc/protos/video_search.proto\x12\x0cvideo_search\"\"\n\rIngestRequest\x12\x11\n\tvideo_url\x18\x01 \x01(\t\"1\n\x0eIngestResponse\x12\x0e\n\x06job_id\x18\x01 \x01(\t\x12\x0f\n\x07message\x18\x02 \x01(\t\"\"\n\x10JobStatusRequest\x12\x0e\n\x06job_id\x18\x01 \x01(\t\"4\n\x11JobStatusResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\x12\x0f\n\x07message\x18\x02 \x01(\t\"2\n\rSearchRequest\x12\x12\n\nquery_text\x18\x01 \x01(\t\x12\r\n\x05limit\x18\x02 \x01(\x05\"p\n\x0cSearchResult\x12\x12\n\nyoutube_id\x18\x01 \x01(\t\x12\x11\n\tscene_idx\x18\x02 \x01(\x05\x12\x12\n\nstart_time\x18\x03 \x01(\x02\x12\x10\n\x08\x65nd_time\x18\x04 \x01(\x02\x12\x13\n\x0bmatch_score\x18\x05 \x01(\x02\"=\n\x0eSearchResponse\x12+\n\x07results\x18\x01 \x03(\x0b\x32\x1a.video_search.SearchResult2\xf9\x01\n\x12VideoSearchService\x12H\n\x0bIngestVideo\x12\x1b.video_search.IngestRequest\x1a\x1c.video_search.IngestResponse\x12H\n\x0bSearchVideo\x12\x1b.video_search.SearchRequest\x1a\x1c.video_search.SearchResponse\x12O\n\x0cGetJobStatus\x12\x1e.video_search.JobStatusRequest\x1a\x1f.video_search.JobStatusResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'src.protos.video_search_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_INGESTREQUEST']._serialized_start=47
  _globals['_INGESTREQUEST']._serialized_end=81
  _globals['_INGESTRESPONSE']._serialized_start=83
  _globals['_INGESTRESPONSE']._serialized_end=132
  _globals['_JOBSTATUSREQUEST']._serialized_start=134
  _globals['_JOBSTATUSREQUEST']._serialized_end=168
  _globals['_JOBSTATUSRESPONSE']._serialized_start=170
  _globals['_JOBSTATUSRESPONSE']._serialized_end=222
  _globals['_SEARCHREQUEST']._serialized_start=224
  _globals['_SEARCHREQUEST']._serialized_end=274
  _globals['_SEARCHRESULT']._serialized_start=276
  _globals['_SEARCHRESULT']._serialized_end=388
  _globals['_SEARCHRESPONSE']._serialized_start=390
  _globals['_SEARCHRESPONSE']._serialized_end=451
  _globals['_VIDEOSEARCHSERVICE']._serialized_start=454
  _globals['_VIDEOSEARCHSERVICE']._serialized_end=703
# @@protoc_insertion_point(module_scope)
